import "../globals.css";

export const metadata = {
  title      : 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}



// import "../globals.css";
// import NavBar from "@/components/Navbar";

// export const metadata = {
//   title: "My First Next App",
//   description: "Generated by create next app"
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <NavBar />
//         <div className = " mx-[6rem]">
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }
